/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: goIsoEx.swigcxx

package goIsoEx

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
typedef _gostring_ swig_type_2;
typedef _gostring_ swig_type_3;
typedef _gostring_ swig_type_4;
typedef _gostring_ swig_type_5;
typedef _gostring_ swig_type_6;
typedef _gostring_ swig_type_7;
typedef _gostring_ swig_type_8;
typedef _gostring_ swig_type_9;
typedef _gostring_ swig_type_10;
typedef _gostring_ swig_type_11;
typedef _gostring_ swig_type_12;
typedef _gostring_ swig_type_13;
typedef _gostring_ swig_type_14;
typedef _gostring_ swig_type_15;
typedef _gostring_ swig_type_16;
typedef _gostring_ swig_type_17;
extern void _wrap_Swig_free_goIsoEx_2f035b14d10877ca(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_goIsoEx_2f035b14d10877ca(swig_intgo arg1);
extern swig_intgo _wrap_MAX_ISO_DATA_goIsoEx_2f035b14d10877ca(void);
extern void _wrap_IsoTabEx_len_set_goIsoEx_2f035b14d10877ca(uintptr_t arg1, short arg2);
extern short _wrap_IsoTabEx_len_get_goIsoEx_2f035b14d10877ca(uintptr_t arg1);
extern void _wrap_IsoTabEx_Xtype_set_goIsoEx_2f035b14d10877ca(uintptr_t arg1, char arg2);
extern char _wrap_IsoTabEx_Xtype_get_goIsoEx_2f035b14d10877ca(uintptr_t arg1);
extern uintptr_t _wrap_new_IsoTabEx_goIsoEx_2f035b14d10877ca(void);
extern void _wrap_delete_IsoTabEx_goIsoEx_2f035b14d10877ca(uintptr_t arg1);
extern void _wrap_IsoField_bitf_set_goIsoEx_2f035b14d10877ca(uintptr_t arg1, short arg2);
extern short _wrap_IsoField_bitf_get_goIsoEx_2f035b14d10877ca(uintptr_t arg1);
extern void _wrap_IsoField_len_set_goIsoEx_2f035b14d10877ca(uintptr_t arg1, short arg2);
extern short _wrap_IsoField_len_get_goIsoEx_2f035b14d10877ca(uintptr_t arg1);
extern void _wrap_IsoField_off_set_goIsoEx_2f035b14d10877ca(uintptr_t arg1, short arg2);
extern short _wrap_IsoField_off_get_goIsoEx_2f035b14d10877ca(uintptr_t arg1);
extern uintptr_t _wrap_new_IsoField_goIsoEx_2f035b14d10877ca(void);
extern void _wrap_delete_IsoField_goIsoEx_2f035b14d10877ca(uintptr_t arg1);
extern void _wrap_IsoEx_dbuf_set_goIsoEx_2f035b14d10877ca(uintptr_t arg1, swig_voidp arg2);
extern swig_voidp _wrap_IsoEx_dbuf_get_goIsoEx_2f035b14d10877ca(uintptr_t arg1);
extern void _wrap_IsoEx_off_set_goIsoEx_2f035b14d10877ca(uintptr_t arg1, short arg2);
extern short _wrap_IsoEx_off_get_goIsoEx_2f035b14d10877ca(uintptr_t arg1);
extern void _wrap_IsoEx_msgtype_set_goIsoEx_2f035b14d10877ca(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_IsoEx_msgtype_get_goIsoEx_2f035b14d10877ca(uintptr_t arg1);
extern void _wrap_IsoEx_bittype_set_goIsoEx_2f035b14d10877ca(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_IsoEx_bittype_get_goIsoEx_2f035b14d10877ca(uintptr_t arg1);
extern void _wrap_IsoEx_vartype_set_goIsoEx_2f035b14d10877ca(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_IsoEx_vartype_get_goIsoEx_2f035b14d10877ca(uintptr_t arg1);
extern void _wrap_IsoEx_msgid_set_goIsoEx_2f035b14d10877ca(uintptr_t arg1, swig_type_1 arg2);
extern swig_type_2 _wrap_IsoEx_msgid_get_goIsoEx_2f035b14d10877ca(uintptr_t arg1);
extern void _wrap_IsoEx_f_set_goIsoEx_2f035b14d10877ca(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_IsoEx_f_get_goIsoEx_2f035b14d10877ca(uintptr_t arg1);
extern void _wrap_IsoEx_deftab_set_goIsoEx_2f035b14d10877ca(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_IsoEx_deftab_get_goIsoEx_2f035b14d10877ca(uintptr_t arg1);
extern uintptr_t _wrap_new_IsoEx_goIsoEx_2f035b14d10877ca(void);
extern void _wrap_delete_IsoEx_goIsoEx_2f035b14d10877ca(uintptr_t arg1);
extern void _wrap_EBcd2Asc_goIsoEx_2f035b14d10877ca(swig_type_3 arg1, swig_type_4 arg2, swig_intgo arg3);
extern void _wrap_Asc2EBcd_goIsoEx_2f035b14d10877ca(swig_type_5 arg1, swig_type_6 arg2, swig_intgo arg3);
extern void _wrap_AtoE_goIsoEx_2f035b14d10877ca(swig_type_7 arg1, swig_intgo arg2);
extern void _wrap_EtoA_goIsoEx_2f035b14d10877ca(swig_type_8 arg1, swig_intgo arg2);
extern void _wrap_Asc2Bcd_goIsoEx_2f035b14d10877ca(swig_type_9 arg1, swig_type_10 arg2, swig_intgo arg3, swig_intgo arg4);
extern void _wrap_Bcd2Asc_goIsoEx_2f035b14d10877ca(swig_type_11 arg1, swig_type_12 arg2, swig_intgo arg3, swig_intgo arg4);
extern swig_intgo _wrap_InitIsoEx_goIsoEx_2f035b14d10877ca(uintptr_t arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4, uintptr_t arg5);
extern swig_intgo _wrap_Str2IsoEx_goIsoEx_2f035b14d10877ca(uintptr_t arg1, swig_type_13 arg2, swig_intgo arg3);
extern swig_intgo _wrap_Iso2StrEx_goIsoEx_2f035b14d10877ca(uintptr_t arg1, swig_type_14 arg2, swig_intgo arg3);
extern swig_intgo _wrap_SetBitEx_goIsoEx_2f035b14d10877ca(uintptr_t arg1, swig_intgo arg2, swig_type_15 arg3, swig_intgo arg4);
extern swig_intgo _wrap_GetBitEx_goIsoEx_2f035b14d10877ca(uintptr_t arg1, swig_intgo arg2, swig_type_16 arg3, swig_intgo arg4);
extern swig_intgo _wrap_ExportIso_goIsoEx_2f035b14d10877ca(swig_type_17 arg1, uintptr_t arg2);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_goIsoEx_2f035b14d10877ca(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func _swig_getMAX_ISO_DATA() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_MAX_ISO_DATA_goIsoEx_2f035b14d10877ca())
	return swig_r
}

var MAX_ISO_DATA int = _swig_getMAX_ISO_DATA()
const MIN_ISO_LEN int = 10
const FIELD_MAX_SIZE int = 512
const ISO_LEN_MASK int = 0x03
const ISO_LEN_FIX int = 0x00
const ISO_LEN_VAR2 int = 0x01
const ISO_LEN_VAR3 int = 0x02
const ISOLV3 int = 0x80
const ISOLV2 int = 0x40
const ISOLFIX int = 0x00
const ISO_DATA_MASK int = 0x3C
const ISODEBC int = 0x20
const ISODBIN int = 0x10
const ISODBCD int = 0x08
const ISODC_D int = 0x04
const ISODASC int = 0x00
const ISO_FIL_MASK int = 0x02
const ISOFSP int = 0x02
const ISOF0 int = 0x00
const ISO_JUST_MASK int = 0x01
const ISORJUST int = 0x01
const ISOLJUST int = 0x00
type SwigcptrIsoTabEx uintptr

func (p SwigcptrIsoTabEx) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrIsoTabEx) SwigIsIsoTabEx() {
}

func (arg1 SwigcptrIsoTabEx) SetLen(arg2 int16) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IsoTabEx_len_set_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0), C.short(_swig_i_1))
}

func (arg1 SwigcptrIsoTabEx) GetLen() (_swig_ret int16) {
	var swig_r int16
	_swig_i_0 := arg1
	swig_r = (int16)(C._wrap_IsoTabEx_len_get_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrIsoTabEx) SetXtype(arg2 byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IsoTabEx_Xtype_set_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0), C.char(_swig_i_1))
}

func (arg1 SwigcptrIsoTabEx) GetXtype() (_swig_ret byte) {
	var swig_r byte
	_swig_i_0 := arg1
	swig_r = (byte)(C._wrap_IsoTabEx_Xtype_get_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewIsoTabEx() (_swig_ret IsoTabEx) {
	var swig_r IsoTabEx
	swig_r = (IsoTabEx)(SwigcptrIsoTabEx(C._wrap_new_IsoTabEx_goIsoEx_2f035b14d10877ca()))
	return swig_r
}

func DeleteIsoTabEx(arg1 IsoTabEx) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_IsoTabEx_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0))
}

type IsoTabEx interface {
	Swigcptr() uintptr
	SwigIsIsoTabEx()
	SetLen(arg2 int16)
	GetLen() (_swig_ret int16)
	SetXtype(arg2 byte)
	GetXtype() (_swig_ret byte)
}

type SwigcptrIsoField uintptr

func (p SwigcptrIsoField) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrIsoField) SwigIsIsoField() {
}

func (arg1 SwigcptrIsoField) SetBitf(arg2 int16) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IsoField_bitf_set_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0), C.short(_swig_i_1))
}

func (arg1 SwigcptrIsoField) GetBitf() (_swig_ret int16) {
	var swig_r int16
	_swig_i_0 := arg1
	swig_r = (int16)(C._wrap_IsoField_bitf_get_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrIsoField) SetLen(arg2 int16) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IsoField_len_set_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0), C.short(_swig_i_1))
}

func (arg1 SwigcptrIsoField) GetLen() (_swig_ret int16) {
	var swig_r int16
	_swig_i_0 := arg1
	swig_r = (int16)(C._wrap_IsoField_len_get_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrIsoField) SetOff(arg2 int16) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IsoField_off_set_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0), C.short(_swig_i_1))
}

func (arg1 SwigcptrIsoField) GetOff() (_swig_ret int16) {
	var swig_r int16
	_swig_i_0 := arg1
	swig_r = (int16)(C._wrap_IsoField_off_get_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewIsoField() (_swig_ret IsoField) {
	var swig_r IsoField
	swig_r = (IsoField)(SwigcptrIsoField(C._wrap_new_IsoField_goIsoEx_2f035b14d10877ca()))
	return swig_r
}

func DeleteIsoField(arg1 IsoField) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_IsoField_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0))
}

type IsoField interface {
	Swigcptr() uintptr
	SwigIsIsoField()
	SetBitf(arg2 int16)
	GetBitf() (_swig_ret int16)
	SetLen(arg2 int16)
	GetLen() (_swig_ret int16)
	SetOff(arg2 int16)
	GetOff() (_swig_ret int16)
}

type SwigcptrIsoEx uintptr

func (p SwigcptrIsoEx) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrIsoEx) SwigIsIsoEx() {
}

func (arg1 SwigcptrIsoEx) SetDbuf(arg2 *byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IsoEx_dbuf_set_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrIsoEx) GetDbuf() (_swig_ret *byte) {
	var swig_r *byte
	_swig_i_0 := arg1
	swig_r = (*byte)(C._wrap_IsoEx_dbuf_get_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrIsoEx) SetOff(arg2 int16) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IsoEx_off_set_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0), C.short(_swig_i_1))
}

func (arg1 SwigcptrIsoEx) GetOff() (_swig_ret int16) {
	var swig_r int16
	_swig_i_0 := arg1
	swig_r = (int16)(C._wrap_IsoEx_off_get_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0)))
	return swig_r
}

const BCDMSG int = 0
const ASCMSG int = 1
func (arg1 SwigcptrIsoEx) SetMsgtype(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IsoEx_msgtype_set_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrIsoEx) GetMsgtype() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_IsoEx_msgtype_get_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0)))
	return swig_r
}

const BCDBIT int = 0
const ASCBIT int = 1
func (arg1 SwigcptrIsoEx) SetBittype(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IsoEx_bittype_set_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrIsoEx) GetBittype() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_IsoEx_bittype_get_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0)))
	return swig_r
}

const BCDVAR int = 0
const ASCVAR int = 1
const HEXVAR int = 2
func (arg1 SwigcptrIsoEx) SetVartype(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IsoEx_vartype_set_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrIsoEx) GetVartype() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_IsoEx_vartype_get_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrIsoEx) SetMsgid(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IsoEx_msgid_set_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0), *(*C.swig_type_1)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrIsoEx) GetMsgid() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_IsoEx_msgid_get_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrIsoEx) SetF(arg2 IsoField) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_IsoEx_f_set_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrIsoEx) GetF() (_swig_ret IsoField) {
	var swig_r IsoField
	_swig_i_0 := arg1
	swig_r = (IsoField)(SwigcptrIsoField(C._wrap_IsoEx_f_get_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrIsoEx) SetDeftab(arg2 IsoTabEx) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_IsoEx_deftab_set_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrIsoEx) GetDeftab() (_swig_ret IsoTabEx) {
	var swig_r IsoTabEx
	_swig_i_0 := arg1
	swig_r = (IsoTabEx)(SwigcptrIsoTabEx(C._wrap_IsoEx_deftab_get_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewIsoEx() (_swig_ret IsoEx) {
	var swig_r IsoEx
	swig_r = (IsoEx)(SwigcptrIsoEx(C._wrap_new_IsoEx_goIsoEx_2f035b14d10877ca()))
	return swig_r
}

func DeleteIsoEx(arg1 IsoEx) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_IsoEx_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0))
}

type IsoEx interface {
	Swigcptr() uintptr
	SwigIsIsoEx()
	SetDbuf(arg2 *byte)
	GetDbuf() (_swig_ret *byte)
	SetOff(arg2 int16)
	GetOff() (_swig_ret int16)
	SetMsgtype(arg2 int)
	GetMsgtype() (_swig_ret int)
	SetBittype(arg2 int)
	GetBittype() (_swig_ret int)
	SetVartype(arg2 int)
	GetVartype() (_swig_ret int)
	SetMsgid(arg2 string)
	GetMsgid() (_swig_ret string)
	SetF(arg2 IsoField)
	GetF() (_swig_ret IsoField)
	SetDeftab(arg2 IsoTabEx)
	GetDeftab() (_swig_ret IsoTabEx)
}

func EBcd2Asc(arg1 string, arg2 string, arg3 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_EBcd2Asc_goIsoEx_2f035b14d10877ca(*(*C.swig_type_3)(unsafe.Pointer(&_swig_i_0)), *(*C.swig_type_4)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func Asc2EBcd(arg1 string, arg2 string, arg3 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_Asc2EBcd_goIsoEx_2f035b14d10877ca(*(*C.swig_type_5)(unsafe.Pointer(&_swig_i_0)), *(*C.swig_type_6)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func AtoE(arg1 string, arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_AtoE_goIsoEx_2f035b14d10877ca(*(*C.swig_type_7)(unsafe.Pointer(&_swig_i_0)), C.swig_intgo(_swig_i_1))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
}

func EtoA(arg1 string, arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_EtoA_goIsoEx_2f035b14d10877ca(*(*C.swig_type_8)(unsafe.Pointer(&_swig_i_0)), C.swig_intgo(_swig_i_1))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
}

func Asc2Bcd(arg1 string, arg2 string, arg3 int, arg4 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_Asc2Bcd_goIsoEx_2f035b14d10877ca(*(*C.swig_type_9)(unsafe.Pointer(&_swig_i_0)), *(*C.swig_type_10)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func Bcd2Asc(arg1 string, arg2 string, arg3 int, arg4 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_Bcd2Asc_goIsoEx_2f035b14d10877ca(*(*C.swig_type_11)(unsafe.Pointer(&_swig_i_0)), *(*C.swig_type_12)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func InitIsoEx(arg1 IsoEx, arg2 int, arg3 int, arg4 int, arg5 IsoTabEx) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5.Swigcptr()
	swig_r = (int)(C._wrap_InitIsoEx_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3), C.uintptr_t(_swig_i_4)))
	return swig_r
}

func Str2IsoEx(arg1 IsoEx, arg2 string, arg3 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_Str2IsoEx_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0), *(*C.swig_type_13)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func Iso2StrEx(arg1 IsoEx, arg2 string, arg3 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_Iso2StrEx_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0), *(*C.swig_type_14)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func SetBitEx(arg1 IsoEx, arg2 int, arg3 string, arg4 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_SetBitEx_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), *(*C.swig_type_15)(unsafe.Pointer(&_swig_i_2)), C.swig_intgo(_swig_i_3)))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func GetBitEx(arg1 IsoEx, arg2 int, arg3 string, arg4 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_GetBitEx_goIsoEx_2f035b14d10877ca(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), *(*C.swig_type_16)(unsafe.Pointer(&_swig_i_2)), C.swig_intgo(_swig_i_3)))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func ExportIso(arg1 string, arg2 IsoTabEx) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (int)(C._wrap_ExportIso_goIsoEx_2f035b14d10877ca(*(*C.swig_type_17)(unsafe.Pointer(&_swig_i_0)), C.uintptr_t(_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}


